import React, { useState } from 'react';
import { 
  ShieldCheck, Server, Cpu, Database, Activity, GitFork, 
  Workflow, CheckCircle2, Download, FileText, Lock, Globe, 
  Zap, Award, AlertTriangle, Key, Terminal, ArrowRight, ExternalLink
} from 'lucide-react';

interface EnterpriseFeature {
  id: string;
  title: string;
  category: 'Infrastructure' | 'Compliance' | 'Hardware & Control' | 'Fleet & AI';
  icon: React.ElementType;
  badge: string;
  headline: string;
  description: string;
  technicalSpecs: string[];
  businessImpact: string;
}

export const ENTERPRISE_FEATURES: EnterpriseFeature[] = [
  {
    id: 'hil-can-ethercat',
    title: 'Hardware-in-the-Loop (HIL) & Real-Time CAN/EtherCAT Streamer',
    category: 'Hardware & Control',
    icon: Activity,
    badge: '1 kHz Real-Time',
    headline: 'Bridge digital twin kinematics directly to physical motor drive controllers via CANopen & EtherCAT.',
    description: 'Enables physical bench testing where real motor drives and servo inverters execute the 1 kHz torque commands generated by the 5-layer simulation, validating step-response and latency without risking mechanical arm collisions.',
    technicalSpecs: [
      'CANopen CiA 402 & EtherCAT CoE master integration',
      'Cyclic Synchronous Position (CSP) & Torque (CST) modes at 1 kHz',
      'micro-ROS / FreeRTOS embedded microcontroller bridge',
      'Real-time Linux PREEMPT_RT deterministic kernel support'
    ],
    businessImpact: 'Prevents motor burnout and mechanical gear stripping during early control loop bring-up, saving £50k+ per prototype.'
  },
  {
    id: 'regulatory-dossier',
    title: 'Automated Regulatory Dossier Generator (ISO 10218, ISO 13849 & FDA)',
    category: 'Compliance',
    icon: ShieldCheck,
    badge: 'Audit-Ready PL-e',
    headline: 'One-click formal safety reports with Sistema calculations, FMEA hazard matrices, and E-stop latency verification.',
    description: 'Generates legally binding compliance packages for notified bodies (TÜV, UL, FDA). Automatically maps System 2 hazard detection, workspace velocity limits, and emergency stop brake deceleration to international safety standards.',
    technicalSpecs: [
      'ISO 13849-1 Performance Level (PL-d / PL-e) & MTTFd calculation',
      'ISO 10218-1/2 Industrial & Collaborative Robot Safety bounds',
      'IEC 62061 SIL 2/3 functional safety verification',
      'FDA 510(k) / ISO 14971 Medical Device Risk Management Dossiers'
    ],
    businessImpact: 'Replaces £200k–£500k in third-party safety consulting and accelerates regulatory approval by 6–9 months.'
  },
  {
    id: 'airgapped-vpc',
    title: 'Air-Gapped Dedicated VPC Cluster & Kubernetes Helm Charts',
    category: 'Infrastructure',
    icon: Server,
    badge: 'Zero Telemetry Egress',
    headline: 'Self-hosted deployment on AWS GovCloud, Azure Confidential Computing, or air-gapped on-premise servers.',
    description: 'Fully isolated deployment where zero telemetry, models, or simulation logs leave your corporate firewall. Includes infrastructure-as-code Helm charts for automated cluster autoscaling across NVIDIA A100/H100 GPUs.',
    technicalSpecs: [
      'Kubernetes Helm 3 deployment package for air-gapped clusters',
      'AWS GovCloud / Azure Confidential Computing / On-Prem Bare Metal',
      'Role-Based Access Control (RBAC) with SAML 2.0 / Okta SSO',
      'SOC 2 Type II, ISO 27001, and HIPAA data isolation compliance'
    ],
    businessImpact: 'Satisfies strict defense, aerospace, and medical compliance mandates prohibiting public cloud usage.'
  },
  {
    id: 'vla-finetuning',
    title: 'Custom VLA Model Fine-Tuning & Fleet Telemetry Ingestion',
    category: 'Fleet & AI',
    icon: Cpu,
    badge: 'Vision-Language-Action',
    headline: 'Fine-tune multi-modal physical AI models directly on your proprietary robot fleet trajectories and gripper sensors.',
    description: 'Ingests your real-world camera streams, joint torque histories, and tactile sensor logs to fine-tune the high-level reasoning and path planning engine specifically for your custom tooling and warehouse fixtures.',
    technicalSpecs: [
      'VLA foundation model fine-tuning (Gemini 3.6 / OpenVLA / RT-2)',
      'Automated tactile and gripper torque calibration ingestion',
      'Domain randomization & synthetic trajectory augmentation pipeline',
      'Zero-shot sim-to-real transfer validation metrics'
    ],
    businessImpact: 'Increases pick-and-place success rates on challenging, reflective, or deformable objects from 78% to 99.4%.'
  },
  {
    id: 'fleet-vda5050',
    title: 'Multi-Robot Fleet Orchestration & VDA 5050 AGV Protocol',
    category: 'Fleet & AI',
    icon: Workflow,
    badge: '100+ Robot Swarm',
    headline: 'Fleet-wide traffic management, dynamic path deconfliction, and standard VDA 5050 AMR coordination.',
    description: 'Simulates and orchestrates fleets of 100+ autonomous mobile robots (AMRs) and robotic arms. Implements dynamic multi-agent conflict-based search (CBS) to prevent warehouse gridlocks and optimize logistics throughput.',
    technicalSpecs: [
      'European VDA 5050 AGV / AMR interoperability protocol',
      'Multi-Agent Path Finding (MAPF) with Conflict-Based Search (CBS)',
      'Simulated charging depot management and dynamic job dispatch',
      'Fleet latency telemetry and real-time deadlock recovery triggers'
    ],
    businessImpact: 'Validates multi-robot factory throughput before physical site commissioning, avoiding costly warehouse retrofits.'
  },
  {
    id: 'isaac-omniverse-sync',
    title: 'NVIDIA Isaac Sim USD & Omniverse Live-Sync Gateway',
    category: 'Hardware & Control',
    icon: GitFork,
    badge: 'Omniverse Live-Sync',
    headline: 'Bi-directional Universal Scene Description (USD) streaming with RTX ray tracing and synthetic sensors.',
    description: 'Live-links the AiGenesis 5-layer control engine to NVIDIA Isaac Sim and Omniverse. Stream trajectories directly into photorealistic RTX physics worlds with realistic depth cameras, LiDAR point clouds, and contact dynamics.',
    technicalSpecs: [
      'Universal Scene Description (USD) bi-directional live socket sync',
      'PhysX 5 GPU-accelerated rigid-body and soft-body contact modeling',
      'Synthetic sensor noise synthesis (Gaussian LiDAR, lens distortion)',
      'Direct Isaac ROS bridge for ROS 2 Humble / Iron integration'
    ],
    businessImpact: 'Unifies high-level reasoning and industrial-grade photorealistic physics simulation in a single workflow.'
  },
  {
    id: 'cad-mjcf-ingestion',
    title: 'Automated CAD / STEP / SolidWorks / MuJoCo Kinematic Ingestion',
    category: 'Hardware & Control',
    icon: Database,
    badge: 'Auto-Inertia Mesh',
    headline: 'Direct import and automated convex decomposition for SolidWorks, STEP, Onshape, and MuJoCo XML files.',
    description: 'Eliminates weeks of tedious manual URDF and MJCF preparation. Automatically performs volumetric convex decomposition (V-HACD), calculates inertia tensors, and assigns joint limits directly from CAD assemblies.',
    technicalSpecs: [
      'Automated V-HACD 3D mesh convex collision decomposition',
      'Precise mass matrix and principal moments of inertia calculation',
      'Native export to URDF, SDF, MJCF (MuJoCo), and Isaac Sim USD',
      'Kinematic loop detection and DH-parameter extraction'
    ],
    businessImpact: 'Reduces robot simulation asset onboarding from 2 weeks of engineering labor to under 5 minutes.'
  },
  {
    id: 'dedicated-fra-sla',
    title: '99.999% SLA & Dedicated Field Robotics Architect (FRA)',
    category: 'Infrastructure',
    icon: Award,
    badge: '15-Min Incident SLA',
    headline: 'Dedicated named robotics solutions architect with 24/7/365 mission-critical engineering response.',
    description: 'Your enterprise team is paired with a Senior Robotics Solutions Architect who provides custom driver authoring, URDF kinematic reviews, control loop tuning sessions, and quarterly on-site safety audits.',
    technicalSpecs: [
      '15-minute emergency response SLA for production blocking incidents',
      'Named Senior Robotics Architect with weekly technical syncs',
      'Custom ROS 2 / micro-ROS driver development and code reviews',
      'Annual on-site hardware-in-the-loop audit and deployment review'
    ],
    businessImpact: 'Ensures zero downtime for mission-critical factory automation and medical robotics operations.'
  }
];

export const EnterpriseFeaturesSection: React.FC = () => {
  const [selectedCategory, setSelectedCategory] = useState<string>('All');
  const [activeFeatureId, setActiveFeatureId] = useState<string>(ENTERPRISE_FEATURES[0].id);

  const categories = ['All', 'Hardware & Control', 'Compliance', 'Infrastructure', 'Fleet & AI'];

  const filteredFeatures = selectedCategory === 'All'
    ? ENTERPRISE_FEATURES
    : ENTERPRISE_FEATURES.filter(f => f.category === selectedCategory);

  const activeFeature = ENTERPRISE_FEATURES.find(f => f.id === activeFeatureId) || ENTERPRISE_FEATURES[0];
  const ActiveIcon = activeFeature.icon;

  const handleDownloadSpecSheet = () => {
    const specSheet = {
      title: "AiGenesis Enterprise Physical AI & Robotics Spec Sheet",
      tier: "Enterprise & Safety (£100,000 / month)",
      generatedAt: new Date().toISOString(),
      capabilities: ENTERPRISE_FEATURES.map(f => ({
        name: f.title,
        category: f.category,
        headline: f.headline,
        specs: f.technicalSpecs,
        impact: f.businessImpact
      }))
    };

    const blob = new Blob([JSON.stringify(specSheet, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `AiGenesis-Enterprise-Safety-Specification-${new Date().toISOString().split('T')[0]}.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <section className="bg-slate-900 border border-slate-800 rounded-3xl p-6 sm:p-8 space-y-8 font-sans">
      {/* Header */}
      <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4 border-b border-slate-800 pb-6">
        <div className="space-y-1">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-amber-500/10 text-amber-300 border border-amber-500/30 text-xs font-mono font-semibold">
            <Lock className="w-3.5 h-3.5 text-amber-400" />
            <span>Enterprise & Custom Tier Capabilities</span>
          </div>
          <h2 className="text-xl sm:text-2xl md:text-3xl font-bold text-white font-mono">
            Mission-Critical Physical AI & Industrial Robotics Infrastructure
          </h2>
          <p className="text-xs sm:text-sm text-slate-400 max-w-2xl">
            Engineered for high-stakes OEM robotics, medical surgical systems, and defense fleets requiring zero-risk hardware testing, air-gapped VPCs, and formal ISO/FDA safety compliance.
          </p>
        </div>

        <button
          onClick={handleDownloadSpecSheet}
          className="flex items-center gap-2 px-4 py-2.5 bg-slate-950 hover:bg-slate-800 text-amber-300 border border-amber-500/40 rounded-xl font-mono text-xs font-bold transition-all shadow-md shrink-0 cursor-pointer"
        >
          <Download className="w-4 h-4 text-amber-400" />
          <span>Download Enterprise Spec Sheet</span>
        </button>
      </div>

      {/* Category Filter Pills */}
      <div className="flex items-center gap-2 overflow-x-auto no-scrollbar pb-1">
        {categories.map((cat) => (
          <button
            key={cat}
            onClick={() => setSelectedCategory(cat)}
            className={`px-3.5 py-1.5 rounded-full text-xs font-mono font-semibold whitespace-nowrap transition-all cursor-pointer ${
              selectedCategory === cat
                ? 'bg-amber-500 text-slate-950 font-bold shadow-md shadow-amber-500/20'
                : 'bg-slate-950 text-slate-400 border border-slate-800 hover:text-white hover:border-slate-700'
            }`}
          >
            {cat}
          </button>
        ))}
      </div>

      {/* Interactive Feature Explorer Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left Column: Feature Navigation List */}
        <div className="lg:col-span-5 space-y-2.5 max-h-[560px] overflow-y-auto pr-1 no-scrollbar">
          {filteredFeatures.map((feature) => {
            const Icon = feature.icon;
            const isSelected = feature.id === activeFeatureId;

            return (
              <div
                key={feature.id}
                onClick={() => setActiveFeatureId(feature.id)}
                className={`p-4 rounded-2xl border transition-all cursor-pointer text-left ${
                  isSelected
                    ? 'bg-slate-950 border-amber-500/80 shadow-lg shadow-amber-500/10'
                    : 'bg-slate-950/60 border-slate-800/80 hover:border-slate-700 hover:bg-slate-950'
                }`}
              >
                <div className="flex items-start justify-between gap-2">
                  <div className="flex items-center gap-2.5">
                    <div className={`p-2 rounded-xl border ${
                      isSelected
                        ? 'bg-amber-500/10 border-amber-500/40 text-amber-400'
                        : 'bg-slate-900 border-slate-800 text-slate-400'
                    }`}>
                      <Icon className="w-4 h-4" />
                    </div>
                    <div>
                      <h4 className="text-xs font-bold text-white font-mono leading-tight">
                        {feature.title}
                      </h4>
                      <span className="text-[10px] text-slate-400 font-mono">
                        {feature.category}
                      </span>
                    </div>
                  </div>
                  <span className={`px-2 py-0.5 rounded-full text-[10px] font-mono font-bold shrink-0 ${
                    isSelected ? 'bg-amber-500/20 text-amber-300 border border-amber-500/40' : 'bg-slate-900 text-slate-500'
                  }`}>
                    {feature.badge}
                  </span>
                </div>
              </div>
            );
          })}
        </div>

        {/* Right Column: Deep-Dive Technical Detail Panel */}
        <div className="lg:col-span-7 bg-slate-950 border border-slate-800 rounded-2xl p-6 flex flex-col justify-between space-y-6">
          <div className="space-y-4">
            <div className="flex flex-wrap items-center justify-between gap-2 border-b border-slate-900 pb-4">
              <div className="flex items-center gap-3">
                <div className="p-2.5 rounded-xl bg-amber-500/10 border border-amber-500/30 text-amber-400">
                  <ActiveIcon className="w-5 h-5" />
                </div>
                <div>
                  <span className="text-[10px] font-mono font-bold uppercase tracking-wider text-amber-400">
                    {activeFeature.category} • Enterprise Deliverable
                  </span>
                  <h3 className="text-base sm:text-lg font-bold text-white font-mono">
                    {activeFeature.title}
                  </h3>
                </div>
              </div>
              <span className="px-2.5 py-1 rounded-full bg-amber-500/10 border border-amber-500/30 text-amber-300 font-mono text-xs font-bold">
                {activeFeature.badge}
              </span>
            </div>

            <p className="text-xs sm:text-sm text-slate-300 leading-relaxed font-sans font-medium">
              {activeFeature.headline}
            </p>

            <p className="text-xs text-slate-400 leading-relaxed font-sans">
              {activeFeature.description}
            </p>

            {/* Technical Specifications */}
            <div className="space-y-2 pt-2">
              <span className="text-[11px] font-mono font-bold text-slate-300 uppercase tracking-wider block">
                Technical Specifications & Architecture:
              </span>
              <ul className="space-y-1.5 text-xs text-slate-300 font-mono">
                {activeFeature.technicalSpecs.map((spec, i) => (
                  <li key={i} className="flex items-start gap-2 bg-slate-900/80 p-2 rounded-lg border border-slate-800/80">
                    <CheckCircle2 className="w-3.5 h-3.5 text-amber-400 shrink-0 mt-0.5" />
                    <span>{spec}</span>
                  </li>
                ))}
              </ul>
            </div>

            {/* Business Impact Banner */}
            <div className="p-3.5 bg-gradient-to-r from-amber-500/10 via-slate-900 to-amber-500/5 border border-amber-500/30 rounded-xl font-mono text-xs text-amber-200 flex items-start gap-2.5">
              <Award className="w-4 h-4 text-amber-400 shrink-0 mt-0.5" />
              <div>
                <strong className="text-amber-300">Financial & Regulatory Impact: </strong>
                <span>{activeFeature.businessImpact}</span>
              </div>
            </div>
          </div>

          <div className="pt-4 border-t border-slate-900 flex flex-col sm:flex-row items-center justify-between gap-3 text-xs font-mono">
            <span className="text-slate-400 text-[11px]">
              Available on <strong>Enterprise & Safety (£100k/mo)</strong> and Custom CapEx site licenses.
            </span>
            <button
              onClick={handleDownloadSpecSheet}
              className="inline-flex items-center gap-1.5 text-amber-300 hover:text-amber-200 font-bold"
            >
              <span>Export Technical PDF/JSON</span>
              <ArrowRight className="w-3.5 h-3.5" />
            </button>
          </div>
        </div>
      </div>
    </section>
  );
};
